<x-guest-layout>
    <div class="mb-7"><div class="flex items-center justify-between"><span class="grid size-12 place-items-center rounded-2xl bg-emerald-100 text-2xl">⌁</span><span class="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">PORTAL AMAN</span></div><h2 class="mt-5 text-3xl font-black tracking-tight text-slate-950">Selamat datang kembali</h2><p class="mt-2 text-sm leading-relaxed text-slate-500">Masuk menggunakan akun sekolah untuk melanjutkan ke dashboard Anda.</p></div>
    <x-auth-session-status class="mb-5 rounded-xl bg-emerald-50 p-3 text-sm text-emerald-800" :status="session('status')" />
    <form method="POST" action="{{ route('login') }}" x-data="{showPassword:false,loading:false}" @submit="loading=true" class="space-y-5">@csrf
        <label class="block"><span class="text-sm font-bold text-slate-700">Alamat email</span><div class="relative mt-2"><span class="pointer-events-none absolute inset-y-0 left-0 grid w-12 place-items-center text-slate-400">@</span><input id="email" class="h-13 w-full rounded-2xl border-slate-200 bg-slate-50 pl-12 pr-4 text-sm transition focus:border-emerald-500 focus:bg-white focus:ring-emerald-500" type="email" name="email" value="{{ old('email') }}" required autofocus autocomplete="username" placeholder="nama@sekolah.sch.id"></div><x-input-error :messages="$errors->get('email')" class="mt-2" /></label>
        <label class="block"><span class="text-sm font-bold text-slate-700">Kata sandi</span><div class="relative mt-2"><span class="pointer-events-none absolute inset-y-0 left-0 grid w-12 place-items-center text-slate-400">●</span><input id="password" class="h-13 w-full rounded-2xl border-slate-200 bg-slate-50 pl-12 pr-14 text-sm transition focus:border-emerald-500 focus:bg-white focus:ring-emerald-500" :type="showPassword?'text':'password'" name="password" required autocomplete="current-password" placeholder="Masukkan kata sandi"><button type="button" @click="showPassword=!showPassword" class="absolute inset-y-0 right-0 px-4 text-xs font-bold text-emerald-700" x-text="showPassword?'Tutup':'Lihat'"></button></div><x-input-error :messages="$errors->get('password')" class="mt-2" /></label>
        <div class="flex items-center justify-between gap-3"><label class="inline-flex items-center gap-2 text-sm text-slate-600"><input id="remember_me" type="checkbox" class="rounded border-slate-300 text-emerald-700 focus:ring-emerald-500" name="remember">Ingat saya</label>@if(Route::has('password.request'))<a class="text-sm font-bold text-emerald-700 hover:text-emerald-900" href="{{ route('password.request') }}">Lupa kata sandi?</a>@endif</div>
        <button class="flex h-13 w-full items-center justify-center gap-2 rounded-2xl bg-gradient-to-r from-emerald-800 to-teal-700 px-5 font-bold text-white shadow-lg shadow-emerald-900/20 transition hover:-translate-y-0.5 hover:shadow-xl disabled:opacity-70" :disabled="loading"><span x-show="!loading">Masuk ke Portal</span><span x-show="loading" x-cloak>Memproses…</span><span x-show="!loading">→</span></button>
    </form>
    <div class="mt-7 border-t border-slate-100 pt-5"><p class="text-center text-xs text-slate-400">Gunakan akun yang diberikan administrator sekolah.</p></div>
</x-guest-layout>
