@extends('layouts.public')
@section('content')
<section class="relative min-h-screen overflow-hidden bg-emerald-950 pt-20 text-white">
    <div class="absolute inset-0 opacity-30 [background-image:radial-gradient(circle_at_70%_20%,#34d399_0,transparent_28%),radial-gradient(circle_at_20%_80%,#fbbf24_0,transparent_20%)]"></div>
    <div class="relative mx-auto grid min-h-[calc(100vh-5rem)] max-w-7xl items-center gap-12 px-5 py-20 lg:grid-cols-2 lg:px-8">
        <div><span class="inline-flex rounded-full border border-emerald-400/30 bg-emerald-400/10 px-4 py-2 text-xs font-bold uppercase tracking-[.2em] text-emerald-200">Pendidikan Indonesia 2026</span><h1 class="mt-7 text-5xl font-black leading-[1.02] tracking-tight sm:text-7xl">Belajar hari ini.<br><span class="text-amber-300">Memimpin esok.</span></h1><p class="mt-7 max-w-xl text-lg leading-8 text-emerald-100">{{ $school?->short_description }}</p><div class="mt-9 flex flex-wrap gap-4"><a href="#profil" class="rounded-full bg-amber-400 px-7 py-3.5 font-bold text-emerald-950 shadow-xl shadow-amber-400/20">Lihat Profil</a><a href="#ppdb" class="rounded-full border border-white/30 px-7 py-3.5 font-bold hover:bg-white/10">Daftar PPDB</a></div></div>
        <div class="relative"><div class="aspect-[4/5] overflow-hidden rounded-[3rem] border border-white/15 bg-gradient-to-br from-emerald-700 to-emerald-900 p-8 shadow-2xl"><div class="flex h-full flex-col justify-between rounded-[2.2rem] bg-white/10 p-8 backdrop-blur"><div class="text-right text-7xl">✦</div><div><div class="text-6xl font-black text-amber-300">A</div><p class="mt-2 text-xl font-bold">Terakreditasi Unggul</p><p class="mt-2 text-emerald-100">Lingkungan aman, inklusif, dan berorientasi masa depan.</p></div></div></div></div>
    </div>
</section>
<section id="profil" class="px-5 py-24 lg:px-8"><div class="mx-auto max-w-7xl"><p class="text-sm font-bold uppercase tracking-[.2em] text-emerald-700">Tentang kami</p><div class="mt-4 grid gap-10 lg:grid-cols-2"><h2 class="text-4xl font-black tracking-tight sm:text-5xl">Sekolah bukan sekadar gedung. Ini ruang untuk bertumbuh.</h2><div><p class="text-lg leading-8 text-slate-600">{{ $school?->tagline }} menjadi napas dalam pembelajaran, pengembangan karakter, dan kolaborasi dengan keluarga.</p><dl class="mt-8 grid grid-cols-3 gap-3">@foreach([['A','Akreditasi'],[$school?->founded_year,'Berdiri'],[$school?->level,'Jenjang']] as [$value,$label])<div class="rounded-2xl bg-white p-5 shadow-sm"><dt class="text-2xl font-black text-emerald-800">{{ $value }}</dt><dd class="mt-1 text-xs text-slate-500">{{ $label }}</dd></div>@endforeach</dl></div></div></div></section>
<section id="program" class="bg-white px-5 py-24 lg:px-8"><div class="mx-auto max-w-7xl"><h2 class="text-4xl font-black">Pengalaman belajar yang utuh</h2><div class="mt-10 grid gap-5 md:grid-cols-3">@foreach([['01','Akademik Adaptif','Pembelajaran berbasis kompetensi dan data perkembangan siswa.'],['02','Karakter & Kepemimpinan','Menumbuhkan empati, integritas, dan keberanian mengambil peran.'],['03','Teknologi Bermakna','Literasi digital untuk berkarya, memecahkan masalah, dan berkolaborasi.']] as [$no,$name,$copy])<article class="rounded-3xl border border-slate-100 bg-stone-50 p-8 transition hover:-translate-y-1 hover:shadow-xl"><span class="text-sm font-black text-amber-600">{{ $no }}</span><h3 class="mt-8 text-xl font-bold">{{ $name }}</h3><p class="mt-3 leading-7 text-slate-600">{{ $copy }}</p></article>@endforeach</div></div></section>
<section id="berita" class="px-5 py-24 lg:px-8"><div class="mx-auto max-w-7xl"><div class="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p class="text-sm font-bold uppercase tracking-[.2em] text-emerald-700">Kabar terbaru</p><h2 class="mt-3 text-4xl font-black">Cerita dari sekolah</h2></div><a href="{{ route('news.index') }}" class="font-bold text-emerald-800">Lihat semua berita →</a></div><div class="mt-10 grid gap-5 md:grid-cols-3">@forelse($latestNews as $item)<a href="{{ route('news.show',$item->slug) }}" class="group rounded-3xl bg-white p-7 shadow-sm transition hover:-translate-y-1 hover:shadow-xl"><span class="text-xs font-bold uppercase tracking-wider text-emerald-700">{{ $item->category->name }}</span><h3 class="mt-4 text-xl font-black leading-snug group-hover:text-emerald-800">{{ $item->title }}</h3><p class="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{{ $item->excerpt }}</p><p class="mt-5 text-xs text-slate-400">{{ $item->published_at->translatedFormat('d M Y') }}</p></a>@empty<div class="rounded-3xl bg-white p-8 text-slate-500 md:col-span-3">Berita akan segera hadir.</div>@endforelse</div></div></section>
@endsection
