@extends('layouts.admin',['title'=>'Dashboard','heading'=>'Dashboard'])
@section('content')
@php
$metrics=[
    ['Siswa Aktif',\App\Models\Student::where('status','active')->count(),'emerald','↑'],
    ['Guru Aktif',\App\Models\Teacher::where('status','active')->count(),'sky','◆'],
    ['Rombel',\App\Models\Classroom::where('is_active',true)->count(),'violet','▦'],
    ['Berita Terbit',\App\Models\News::publiclyVisible()->count(),'amber','◧'],
];
$moduleProgress=[['Fondasi & keamanan',100],['Master akademik',100],['Assessment Engine',100],['e-Rapor & portal',100],['Pembelajaran & CBT',0]];
@endphp
<section class="relative overflow-hidden rounded-[2rem] bg-gradient-to-br from-emerald-950 via-emerald-800 to-cyan-800 p-6 text-white shadow-xl sm:p-8"><div class="absolute -right-20 -top-24 size-72 rounded-full bg-cyan-300/20 blur-3xl"></div><div class="absolute bottom-0 right-1/4 size-40 rounded-full bg-amber-300/10 blur-3xl"></div><div class="relative flex flex-wrap items-end justify-between gap-6"><div><span class="rounded-full bg-white/10 px-3 py-1 text-xs font-bold">MANAGEMENT CONSOLE</span><p class="mt-5 text-sm text-emerald-200">Selamat datang kembali</p><h2 class="mt-1 text-3xl font-black sm:text-4xl">{{ auth()->user()->name }}</h2><p class="mt-3 max-w-2xl text-sm leading-6 text-emerald-100 sm:text-base">Pantau data sekolah, kelola konten, akademik, penilaian, dan portal pengguna dari satu pusat kendali.</p></div><div class="flex gap-3"><a href="{{ route('home') }}" target="_blank" class="rounded-2xl bg-white px-5 py-3 text-sm font-black text-emerald-950">Website publik</a>@can('manage_school_profile')<a href="{{ route('admin.school-profile.edit') }}" class="rounded-2xl border border-white/25 px-5 py-3 text-sm font-bold">Pengaturan</a>@endcan</div></div></section>
<div class="mt-6 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach($metrics as [$label,$value,$color,$icon])<article class="group rounded-3xl border border-white bg-white p-5 shadow-sm transition hover:-translate-y-1 hover:shadow-lg sm:p-6"><div class="flex items-center justify-between"><span class="grid size-11 place-items-center rounded-2xl bg-{{ $color }}-100 text-lg font-black text-{{ $color }}-700">{{ $icon }}</span><span class="rounded-full bg-slate-50 px-2 py-1 text-[10px] font-bold text-slate-500">LIVE</span></div><p class="mt-5 text-sm text-slate-500">{{ $label }}</p><p class="mt-1 text-4xl font-black text-slate-950">{{ number_format($value) }}</p></article>@endforeach</div>
<div class="mt-6 grid gap-6 xl:grid-cols-[1.5fr_.8fr]"><section class="rounded-3xl bg-white p-5 shadow-sm sm:p-6"><div class="flex items-center justify-between"><div><p class="text-xs font-black uppercase tracking-widest text-emerald-700">Roadmap</p><h3 class="mt-1 text-xl font-black">Kesiapan Modul</h3></div><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-black text-emerald-700">Phase 1–6 aktif</span></div><div class="mt-6 space-y-5">@foreach($moduleProgress as [$name,$progress])<div><div class="mb-2 flex justify-between text-sm"><span class="font-semibold">{{ $name }}</span><b>{{ $progress }}%</b></div><div class="h-2.5 overflow-hidden rounded-full bg-slate-100"><div class="h-full rounded-full bg-gradient-to-r from-emerald-600 to-cyan-500" style="width:{{ $progress }}%"></div></div></div>@endforeach</div></section>
<section class="rounded-3xl bg-slate-950 p-5 text-white shadow-xl sm:p-6"><p class="text-xs font-black uppercase tracking-widest text-emerald-300">Aksi cepat</p><h3 class="mt-1 text-xl font-black">Mulai bekerja</h3><div class="mt-5 grid gap-3">@can('manage_academic')<a href="{{ route('admin.academic.assignments') }}" class="flex items-center justify-between rounded-2xl bg-white/5 p-4 font-bold hover:bg-white/10"><span>Kelola akademik</span><span>→</span></a>@endcan @can('input_scores')<a href="{{ route('admin.assessment.scores.index') }}" class="flex items-center justify-between rounded-2xl bg-emerald-400 p-4 font-black text-emerald-950"><span>Input nilai</span><span>→</span></a>@endcan @can('manage_cms')<a href="{{ route('admin.content.index','announcements') }}" class="flex items-center justify-between rounded-2xl bg-white/5 p-4 font-bold hover:bg-white/10"><span>Buat pengumuman</span><span>→</span></a>@endcan</div></section></div>
@can('view_academic')<section class="mt-6 rounded-3xl bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs font-black uppercase tracking-widest text-sky-700">Data utama</p><h3 class="mt-1 text-xl font-black">Master Akademik</h3></div><a href="{{ route('admin.academic.timetable') }}" class="rounded-xl bg-sky-50 px-4 py-2 text-sm font-bold text-sky-700">Lihat timetable →</a></div><div class="mt-5 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">@foreach(['academic-years'=>'Tahun Ajaran','semesters'=>'Semester','curricula'=>'Kurikulum','phases'=>'Fase','levels'=>'Jenjang','classrooms'=>'Rombel','subjects'=>'Mapel','teachers'=>'Guru','staff'=>'Staff','students'=>'Siswa','parents'=>'Orang Tua','alumni'=>'Alumni'] as $key=>$name)<a href="{{ route('admin.academic.index',$key) }}" class="rounded-2xl border border-slate-100 bg-slate-50 p-4 text-center text-sm font-bold transition hover:border-emerald-200 hover:bg-emerald-50 hover:text-emerald-800">{{ $name }}</a>@endforeach</div></section>@endcan
@endsection
