@extends('layouts.admin',['title'=>$assessment->title,'heading'=>'Spreadsheet Nilai'])
@section('content')
<meta name="csrf-token" content="{{ csrf_token() }}">
<div x-data="scoreSheet()" class="space-y-5">
<div class="flex flex-wrap items-center justify-between gap-3"><div><h2 class="text-2xl font-black">{{ $assessment->title }}</h2><p class="text-sm text-slate-500">Edit langsung, paste blok dari Excel, dan autosave per siswa.</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('admin.assessment.analysis',$assessment) }}" class="rounded-xl border bg-white px-4 py-2 font-semibold">Analisis</a><a href="{{ route('admin.assessment.scores.export',$assessment) }}" class="rounded-xl border bg-white px-4 py-2 font-semibold">Export Excel</a></div></div>
<form method="POST" action="{{ route('admin.assessment.scores.import',$assessment) }}" enctype="multipart/form-data" class="flex flex-col gap-3 rounded-2xl bg-white p-4 shadow-sm sm:flex-row">@csrf<input type="file" name="file" accept=".xlsx,.xls,.csv" required class="flex-1"><button class="rounded-xl bg-slate-900 px-5 py-2 font-bold text-white">Import Excel</button></form>
<form method="POST" action="{{ route('admin.assessment.scores.update',$assessment) }}">@csrf @method('PUT')<div class="overflow-x-auto rounded-2xl bg-white shadow-sm"><table class="w-full min-w-[800px] text-sm"><thead class="bg-slate-50"><tr><th class="p-4 text-left">NIS</th><th class="p-4 text-left">Nama</th>@foreach($assessment->components as $component)<th class="p-4">{{ $component->name }}<small class="block">{{ $component->weight }}%</small></th>@endforeach<th class="p-4">Akhir</th><th class="p-4">Autosave</th></tr></thead><tbody class="divide-y">
@foreach($scores as $i=>$score)<tr data-row="{{ $i }}"><td class="p-4">{{ $score->student->nis }}</td><td class="p-4 font-semibold">{{ $score->student->name }}<input type="hidden" name="scores[{{ $i }}][student_score_id]" value="{{ $score->id }}"><input type="hidden" name="scores[{{ $i }}][reason]" value="Input spreadsheet"></td>
@foreach($assessment->components as $j=>$component)@php($detail=$score->details->firstWhere('assessment_component_id',$component->id))<td class="p-2"><input type="hidden" name="scores[{{ $i }}][details][{{ $j }}][assessment_component_id]" value="{{ $component->id }}"><input type="hidden" name="scores[{{ $i }}][details][{{ $j }}][weight]" value="{{ $component->weight }}"><input type="hidden" name="scores[{{ $i }}][details][{{ $j }}][max_score]" value="{{ $component->max_score }}"><input data-score-input data-row="{{ $i }}" data-col="{{ $j }}" @input="schedule({{ $i }})" @paste="pasteGrid($event,{{ $i }},{{ $j }})" @keydown.enter.prevent="move($event,1,0)" @keydown.arrow-down.prevent="move($event,1,0)" @keydown.arrow-up.prevent="move($event,-1,0)" type="number" min="0" max="{{ $component->max_score }}" step="0.01" name="scores[{{ $i }}][details][{{ $j }}][score]" value="{{ $detail?->score??0 }}" class="w-24 rounded-lg border-slate-200 text-center" @disabled($score->locked_at)></td>@endforeach
<td id="final-{{ $i }}" class="p-4 text-center font-black">{{ $score->final_score??'—' }}</td><td id="state-{{ $i }}" class="p-4 text-xs text-slate-400">{{ $score->locked_at?'Terkunci':'Siap' }}</td></tr>@endforeach
</tbody></table></div><button class="mt-5 rounded-full bg-emerald-700 px-7 py-3 font-bold text-white">Simpan seluruh nilai</button></form></div>
<script>
function scoreSheet(){return{timers:{},endpoint:@js(route('admin.assessment.scores.autosave',$assessment)),schedule(row){clearTimeout(this.timers[row]);document.getElementById('state-'+row).textContent='Menunggu…';this.timers[row]=setTimeout(()=>this.save(row),700)},rowPayload(row){const tr=document.querySelector(`[data-row="${row}"]`);const fd=new FormData(tr.closest('form'));const prefix=`scores[${row}]`;const details=[];@foreach($assessment->components as $j=>$component)details.push({assessment_component_id:fd.get(`${prefix}[details][{{ $j }}][assessment_component_id]`),weight:fd.get(`${prefix}[details][{{ $j }}][weight]`),max_score:fd.get(`${prefix}[details][{{ $j }}][max_score]`),score:fd.get(`${prefix}[details][{{ $j }}][score]`)});@endforeach return{scores:[{student_score_id:fd.get(`${prefix}[student_score_id]`),reason:'Autosave spreadsheet',details}]};},async save(row){const state=document.getElementById('state-'+row);state.textContent='Menyimpan…';try{const response=await fetch(this.endpoint,{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json','X-CSRF-TOKEN':document.querySelector('meta[name=csrf-token]').content},body:JSON.stringify(this.rowPayload(row))});if(!response.ok)throw new Error();const data=await response.json();document.getElementById('final-'+row).textContent=data.final_score;state.textContent='Tersimpan';}catch(e){state.textContent='Gagal—simpan manual';state.classList.add('text-red-600')}},move(event,rowDelta,colDelta){const el=event.target;document.querySelector(`[data-score-input][data-row="${Number(el.dataset.row)+rowDelta}"][data-col="${Number(el.dataset.col)+colDelta}"]`)?.focus()},pasteGrid(event,startRow,startCol){const rows=event.clipboardData.getData('text').trim().split(/\r?\n/).map(row=>row.split(/\t|;/));if(rows.length===1&&rows[0].length===1)return;event.preventDefault();const touched=new Set;rows.forEach((cols,r)=>cols.forEach((value,c)=>{const input=document.querySelector(`[data-score-input][data-row="${startRow+r}"][data-col="${startCol+c}"]`);if(input&&!input.disabled&&value!==''&&!Number.isNaN(Number(value))){input.value=value;input.dispatchEvent(new Event('input'));touched.add(startRow+r)}}));touched.forEach(row=>this.schedule(row));}}}
</script>
@endsection
