@extends('layouts.admin', ['title'=>(isset($item)?'Edit ':'Tambah ').$label, 'heading'=>(isset($item)?'Edit ':'Tambah ').$label])
@section('content')
@php
$definitions=[
'announcements'=>[['title','Judul','text'],['category','Kategori','select',['Umum','Akademik','PPDB','Ujian','Libur','Kegiatan']],['excerpt','Ringkasan','textarea'],['content','Isi','textarea'],['status','Status','select',['draft','published','scheduled','expired']],['published_at','Tanggal Publikasi','datetime-local'],['expires_at','Tanggal Berakhir','datetime-local'],['is_featured','Unggulan','boolean']],
'events'=>[['title','Judul','text'],['description','Deskripsi','textarea'],['location','Lokasi','text'],['starts_at','Mulai','datetime-local'],['ends_at','Selesai','datetime-local'],['person_in_charge','Penanggung Jawab','text'],['status','Status','select',['draft','published','cancelled']],['is_featured','Unggulan','boolean'],['image','Poster','file']],
'galleries'=>[['title','Nama Album','text'],['category','Kategori','text'],['activity_year','Tahun Kegiatan','number'],['description','Deskripsi','textarea'],['is_published','Publikasikan','boolean'],['image','Sampul Album','file']],
'facilities'=>[['name','Nama Fasilitas','text'],['description','Deskripsi','textarea'],['quantity','Jumlah','number'],['condition','Kondisi','select',['Sangat Baik','Baik','Cukup','Rusak']],['is_published','Publikasikan','boolean'],['image','Foto','file']],
'achievements'=>[['title','Judul Prestasi','text'],['recipient_name','Penerima','text'],['category','Kategori','select',['Akademik','Olahraga','Seni','Keagamaan','Teknologi','Organisasi']],['level','Tingkat','select',['Sekolah','Kecamatan','Kabupaten','Provinsi','Nasional','Internasional']],['achievement_date','Tanggal','date'],['description','Deskripsi','textarea'],['is_published','Publikasikan','boolean'],['image','Foto','file']],
'extracurriculars'=>[['name','Nama','text'],['advisor','Pembina','text'],['schedule','Jadwal','text'],['description','Deskripsi','textarea'],['member_count','Jumlah Anggota','number'],['achievements','Prestasi','textarea'],['is_published','Publikasikan','boolean'],['image','Foto','file']],
'downloads'=>[['title','Judul Dokumen','text'],['category','Kategori','select',['Kalender Akademik','Formulir','Brosur','Surat Edaran','SOP','Tata Tertib','Dokumen Sekolah']],['description','Deskripsi','textarea'],['file','File','document'],['is_published','Publikasikan','boolean']],
'faqs'=>[['question','Pertanyaan','text'],['answer','Jawaban','textarea'],['category','Kategori','text'],['sort_order','Urutan','number'],['is_active','Aktif','boolean']],
'pages'=>[['title','Judul Halaman','text'],['content','Konten','textarea'],['status','Status','select',['draft','published']],['meta_title','Meta Title','text'],['meta_description','Meta Description','textarea'],['sort_order','Urutan','number']],
'banners'=>[['title','Judul','text'],['subtitle','Subjudul','textarea'],['cta_label','Label CTA','text'],['cta_url','URL CTA','text'],['sort_order','Urutan','number'],['starts_at','Mulai','datetime-local'],['ends_at','Selesai','datetime-local'],['is_active','Aktif','boolean'],['image','Gambar','file']],];
$fields=$definitions[$module]; $editing=isset($item);
@endphp
<form method="POST" action="{{ $editing?route('admin.content.update',[$module,$item->id]):route('admin.content.store',$module) }}" enctype="multipart/form-data" class="mx-auto max-w-4xl rounded-2xl bg-white p-6 shadow-sm">@csrf @if($editing)@method('PUT')@endif<div class="grid gap-5 md:grid-cols-2">@foreach($fields as $field)@php([$name,$label,$type]=$field);@php($value=old($name,$item->{$name}??''));<label class="text-sm font-semibold {{ $type==='textarea'?'md:col-span-2':'' }}">{{ $label }}@if($type==='textarea')<textarea name="{{ $name }}" rows="{{ in_array($name,['content','description','answer'])?7:3 }}" class="mt-2 w-full rounded-xl border-slate-200">{{ $value }}</textarea>@elseif($type==='select')<select name="{{ $name }}" class="mt-2 w-full rounded-xl border-slate-200">@foreach($field[3] as $option)<option value="{{ $option }}" @selected($value===$option)>{{ ucfirst($option) }}</option>@endforeach</select>@elseif($type==='boolean')<span class="mt-3 flex items-center gap-3"><input type="hidden" name="{{ $name }}" value="0"><input type="checkbox" name="{{ $name }}" value="1" @checked($value) class="rounded text-emerald-700"> Ya</span>@elseif(in_array($type,['file','document']))<input type="file" name="{{ $name }}" {{ !$editing&&$type==='document'?'required':'' }} accept="{{ $type==='document'?'.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.zip':'image/png,image/jpeg,image/webp' }}" class="mt-2 block w-full text-sm">@else @php($formatted=in_array($type,['datetime-local'])&&$value?\Carbon\Carbon::parse($value)->format('Y-m-d\TH:i'):$value)<input type="{{ $type }}" name="{{ $name }}" value="{{ $formatted }}" class="mt-2 w-full rounded-xl border-slate-200"></label>@endif</label>@endforeach</div><div class="mt-8 flex justify-end gap-3"><a href="{{ route('admin.content.index',$module) }}" class="rounded-full border px-6 py-3 font-semibold">Batal</a><button class="rounded-full bg-emerald-700 px-7 py-3 font-bold text-white">Simpan</button></div></form>
@if($editing && $module==='galleries')<section class="mx-auto mt-6 max-w-4xl rounded-2xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Item galeri</h2><form method="POST" action="{{ route('admin.gallery-items.store',$item) }}" enctype="multipart/form-data" class="mt-5 grid gap-4 md:grid-cols-2">@csrf<label class="text-sm font-semibold">Unggah foto<input type="file" name="images[]" multiple accept="image/png,image/jpeg,image/webp" class="mt-2 block w-full text-sm"></label><label class="text-sm font-semibold">URL video<input type="url" name="video_url" class="mt-2 w-full rounded-xl border-slate-200"></label><label class="text-sm font-semibold md:col-span-2">Caption<input name="caption" class="mt-2 w-full rounded-xl border-slate-200"></label><button class="rounded-full bg-slate-900 px-6 py-3 font-bold text-white md:col-span-2">Tambah ke album</button></form><div class="mt-6 grid grid-cols-2 gap-3 md:grid-cols-4">@foreach($item->items as $galleryItem)<div class="relative overflow-hidden rounded-xl bg-slate-100">@if($galleryItem->file_path)<img src="{{ Storage::url($galleryItem->file_path) }}" class="aspect-square w-full object-cover">@else<div class="grid aspect-square place-items-center p-3 text-center text-xs">{{ $galleryItem->video_url }}</div>@endif<form method="POST" action="{{ route('admin.gallery-items.destroy',$galleryItem) }}" class="absolute right-2 top-2">@csrf @method('DELETE')<button class="rounded-full bg-red-600 px-2 py-1 text-xs text-white">Hapus</button></form></div>@endforeach</div></section>@endif
@endsection
