@extends($print ? 'layouts.report' : 'layouts.admin')
@section('content')
<div class="mx-auto max-w-5xl bg-white p-6 sm:p-10 {{ $print ? '' : 'rounded-3xl shadow-sm' }}"><div class="text-center"><p class="text-sm font-bold tracking-widest text-emerald-700">LAPORAN HASIL BELAJAR</p><h1 class="mt-2 text-2xl font-black">{{ $report->student->name }}</h1><p>{{ $report->student->nis }} · {{ $report->classroom->name }} · {{ $report->semester->name }} {{ $report->academicYear->name }}</p></div>
<div class="mt-8 overflow-x-auto"><table class="w-full border-collapse text-sm"><thead><tr class="bg-slate-100"><th class="border p-3 text-left">Mata Pelajaran</th><th class="border p-3">Nilai</th><th class="border p-3">Predikat</th><th class="border p-3 text-left">Deskripsi</th></tr></thead><tbody>@foreach($report->scores as $score)<tr><td class="border p-3 font-semibold">{{ $score->subject->name }}</td><td class="border p-3 text-center">{{ $score->final_score }}</td><td class="border p-3 text-center">{{ $score->predicate }}</td><td class="border p-3">{{ $score->description }}</td></tr>@endforeach</tbody></table></div>
<div class="mt-6 grid gap-4 sm:grid-cols-2"><div><b>Kehadiran</b><p>Sakit {{ $report->sick_days }}, Izin {{ $report->excused_days }}, Tanpa keterangan {{ $report->unexcused_days }}</p></div><div><b>Keputusan</b><p>{{ $report->promotion_decision ?: 'Belum ditetapkan' }}</p></div></div><p class="mt-4"><b>Catatan wali kelas:</b> {{ $report->homeroom_note ?: '—' }}</p>
@unless($print)<form class="mt-8 space-y-4" method="POST" action="{{ route('admin.reports.update',$report) }}">@csrf @method('PUT')<textarea name="homeroom_note" class="w-full rounded-xl border-slate-300" placeholder="Catatan wali kelas">{{ $report->homeroom_note }}</textarea><div class="grid gap-3 sm:grid-cols-4"><input name="promotion_decision" value="{{ $report->promotion_decision }}" class="rounded-xl border-slate-300" placeholder="Keputusan"><input type="number" name="sick_days" value="{{ $report->sick_days }}" class="rounded-xl border-slate-300"><input type="number" name="excused_days" value="{{ $report->excused_days }}" class="rounded-xl border-slate-300"><input type="number" name="unexcused_days" value="{{ $report->unexcused_days }}" class="rounded-xl border-slate-300"></div><button class="rounded-xl bg-emerald-700 px-5 py-3 font-bold text-white">Simpan rapor</button></form><div class="mt-4 flex flex-wrap gap-2">@foreach(['verified'=>'Verifikasi','published'=>'Terbitkan','locked'=>'Kunci'] as $status=>$label)<form method="POST" action="{{ route('admin.reports.transition',$report) }}">@csrf @method('PATCH')<input type="hidden" name="status" value="{{ $status }}"><button class="rounded-xl border px-4 py-2 font-semibold">{{ $label }}</button></form>@endforeach<a target="_blank" href="{{ route('admin.reports.print',$report) }}" class="rounded-xl border px-4 py-2 font-semibold">Cetak / PDF</a></div>@endunless
<div class="mt-8 flex items-center gap-4 border-t pt-4 text-xs text-slate-500"><div class="shrink-0">{!! QrCode::size(80)->generate(route('reports.verify',$report->verification_token)) !!}</div><div>Verifikasi dokumen:<br>{{ route('reports.verify',$report->verification_token) }}</div></div></div>
@if($print)<script>window.print()</script>@endif
@endsection
