<!doctype html>
<html lang="id">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="csrf-token" content="{{ csrf_token() }}"><meta name="theme-color" content="#020617"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><title>{{ $title ?? 'Dashboard' }} · Smart School</title><link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/icons/smart-school.svg" type="image/svg+xml">@vite(['resources/css/app.css','resources/js/app.js'])</head>
<body class="min-h-screen bg-[#f3f6f8] pb-20 text-slate-900 antialiased lg:pb-0" x-data="pwaShell">
<div x-data="{sidebar:false}" @keydown.escape.window="sidebar=false" class="min-h-screen lg:flex">
    <div x-show="sidebar" x-cloak x-transition.opacity @click="sidebar=false" class="fixed inset-0 z-40 bg-slate-950/60 backdrop-blur-sm lg:hidden"></div>
    <aside :class="sidebar?'translate-x-0':'-translate-x-full'" class="fixed inset-y-0 left-0 z-50 flex w-[19rem] flex-col border-r border-white/5 bg-slate-950 text-slate-300 shadow-2xl transition duration-300 lg:sticky lg:top-0 lg:h-screen lg:translate-x-0">
        <div class="flex h-20 shrink-0 items-center justify-between border-b border-white/5 px-5"><a href="{{ route('dashboard') }}" class="flex min-w-0 items-center gap-3 text-white"><img src="/icons/smart-school.svg" class="size-11 rounded-2xl" alt=""><span class="min-w-0"><b class="block truncate font-black">Smart School</b><small class="block text-xs text-slate-400">Management Console</small></span></a><button @click="sidebar=false" class="grid size-9 place-items-center rounded-xl bg-white/5 text-xl lg:hidden">×</button></div>
        <nav class="flex-1 space-y-1 overflow-y-auto px-4 py-5 text-sm">
            <a href="{{ route('dashboard') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3 font-bold {{ request()->routeIs('dashboard')?'bg-emerald-400 text-emerald-950 shadow-lg shadow-emerald-500/20':'hover:bg-white/5 hover:text-white' }}"><span class="text-lg">⌂</span>Dashboard</a>
            @can('manage_school_profile')<a href="{{ route('admin.school-profile.edit') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3 {{ request()->routeIs('admin.school-profile.*')?'bg-white/10 text-white':'hover:bg-white/5' }}"><span>◆</span>Profil Sekolah</a>@endcan
            @can('view_academic')<div class="px-4 pb-2 pt-6 text-[10px] font-black uppercase tracking-[.2em] text-slate-500">Akademik</div><a href="{{ route('admin.academic.assignments') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3 {{ request()->routeIs('admin.academic.*')?'bg-white/10 text-white':'hover:bg-white/5' }}"><span>▦</span>Master & Penugasan</a><a href="{{ route('admin.academic.timetable') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3 hover:bg-white/5"><span>◫</span>Timetable</a>@endcan
            @can('input_scores')<a href="{{ route('admin.assessment.scores.index') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3 {{ request()->routeIs('admin.assessment.*')?'bg-white/10 text-white':'hover:bg-white/5' }}"><span>✓</span>Penilaian</a>@endcan
            @can('manage_report_cards')<a href="{{ route('admin.reports.index') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3 {{ request()->routeIs('admin.reports.*')?'bg-white/10 text-white':'hover:bg-white/5' }}"><span>▤</span>e-Rapor</a>@endcan
            <div class="px-4 pb-2 pt-6 text-[10px] font-black uppercase tracking-[.2em] text-slate-500">CMS Website</div>
            @can('view_news')<a href="{{ route('admin.news.index') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3 {{ request()->routeIs('admin.news.*')?'bg-white/10 text-white':'hover:bg-white/5' }}"><span>◧</span>Berita</a>@endcan
            @can('manage_news_categories')<a href="{{ route('admin.news-categories.index') }}" class="flex items-center gap-3 rounded-2xl px-4 py-3 hover:bg-white/5"><span>◇</span>Kategori Berita</a>@endcan
            @can('manage_cms')@foreach(['announcements'=>'Pengumuman','events'=>'Agenda','galleries'=>'Galeri','facilities'=>'Fasilitas','achievements'=>'Prestasi','extracurriculars'=>'Ekstrakurikuler','downloads'=>'Download','faqs'=>'FAQ','pages'=>'Halaman','banners'=>'Banner'] as $key=>$name)<a href="{{ route('admin.content.index',$key) }}" class="flex items-center gap-3 rounded-2xl px-4 py-2.5 {{ request('module')===$key?'bg-white/10 text-white':'hover:bg-white/5' }}"><span class="text-slate-500">•</span>{{ $name }}</a>@endforeach@endcan
            <div class="px-4 pb-2 pt-6 text-[10px] font-black uppercase tracking-[.2em] text-slate-500">Portal Role</div>@can('view_teacher_portal')<a href="{{ route('portal.teacher') }}" class="block rounded-2xl px-4 py-2.5 hover:bg-white/5">Portal Guru</a>@endcan @can('view_student_portal')<a href="{{ route('portal.student') }}" class="block rounded-2xl px-4 py-2.5 hover:bg-white/5">Portal Siswa</a>@endcan @can('view_parent_portal')<a href="{{ route('portal.parent.child') }}" class="block rounded-2xl px-4 py-2.5 hover:bg-white/5">Portal Orang Tua</a>@endcan @can('view_principal_dashboard')<a href="{{ route('portal.principal') }}" class="block rounded-2xl px-4 py-2.5 hover:bg-white/5">Dashboard Kepala Sekolah</a>@endcan
        </nav>
        <div class="shrink-0 border-t border-white/5 p-4"><button x-show="installable" x-cloak @click="installApp" class="mb-3 w-full rounded-2xl bg-emerald-400 px-4 py-3 font-black text-emerald-950">↓ Instal aplikasi</button><a href="{{ route('profile.edit') }}" class="flex items-center gap-3 rounded-2xl bg-white/5 p-3"><span class="grid size-10 shrink-0 place-items-center rounded-xl bg-emerald-400 font-black text-emerald-950">{{ str(auth()->user()->name)->substr(0,1)->upper() }}</span><span class="min-w-0"><b class="block truncate text-sm text-white">{{ auth()->user()->name }}</b><small class="block truncate text-slate-400">{{ auth()->user()->roles->pluck('name')->join(', ') }}</small></span></a></div>
    </aside>
    <div class="min-w-0 flex-1"><header class="sticky top-0 z-30 flex h-16 items-center justify-between border-b border-slate-200/80 bg-white/85 px-4 backdrop-blur-xl sm:h-20 sm:px-6 lg:px-8"><div class="flex items-center gap-3"><button @click="sidebar=true" class="grid size-10 place-items-center rounded-xl border border-slate-200 bg-white text-xl lg:hidden">☰</button><div><p class="hidden text-[10px] font-black uppercase tracking-[.18em] text-emerald-700 sm:block">Sistem Informasi Sekolah</p><h1 class="font-black text-slate-950">{{ $heading ?? 'Dashboard' }}</h1></div></div><div class="flex items-center gap-2"><span class="hidden rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700 sm:block" x-text="online?'● Online':'● Offline'"></span><button x-show="installable" x-cloak @click="installApp" class="rounded-xl border px-3 py-2 text-xs font-bold">Instal</button><a href="{{ route('home') }}" target="_blank" class="hidden rounded-xl border px-4 py-2 text-sm font-bold md:block">Lihat Website</a><form method="POST" action="{{ route('logout') }}">@csrf<button class="rounded-xl bg-slate-950 px-4 py-2 text-sm font-bold text-white">Keluar</button></form></div></header>
        <main class="mx-auto max-w-[1600px] p-4 sm:p-6 lg:p-8">@if(session('success'))<div class="mb-6 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{{ session('success') }}</div>@endif @if($errors->any())<div class="mb-6 rounded-2xl border border-red-200 bg-red-50 p-4 text-red-800"><b>Periksa kembali data berikut:</b><ul class="mt-2 list-disc pl-5 text-sm">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif @yield('content')</main>
    </div>
    <nav class="fixed inset-x-3 bottom-3 z-40 grid grid-cols-5 rounded-[1.4rem] border border-white/10 bg-slate-950/95 p-2 text-white shadow-2xl backdrop-blur-xl lg:hidden" style="padding-bottom:max(.5rem,env(safe-area-inset-bottom))"><a href="{{ route('dashboard') }}" class="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-semibold"><span class="text-xl">⌂</span>Home</a>@can('view_news')<a href="{{ route('admin.news.index') }}" class="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-semibold"><span class="text-xl">◧</span>CMS</a>@else<span></span>@endcan @can('view_academic')<a href="{{ route('admin.academic.assignments') }}" class="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-semibold"><span class="text-xl">▦</span>Akademik</a>@else<span></span>@endcan @can('input_scores')<a href="{{ route('admin.assessment.scores.index') }}" class="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-semibold"><span class="text-xl">✓</span>Nilai</a>@else<span></span>@endcan<button @click="sidebar=true" class="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl bg-emerald-400 text-[10px] font-black text-emerald-950"><span class="text-xl">☰</span>Menu</button></nav>
</div></body></html>
