<!doctype html>
<html lang="id">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="csrf-token" content="{{ csrf_token() }}">
    <meta name="theme-color" content="#064e3b"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
    <title>{{ $title ?? 'Portal' }} · Smart School</title><link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/icons/smart-school.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/icons/smart-school.svg">
    @vite(['resources/css/app.css','resources/js/app.js'])
</head>
<body class="min-h-screen bg-[#f3f7f6] font-sans text-slate-900 antialiased" x-data="pwaShell">
@php
$portalHome=auth()->user()->can('view_teacher_portal')?route('portal.teacher'):(auth()->user()->can('view_student_portal')?route('portal.student'):(auth()->user()->can('view_parent_portal')?route('portal.parent.child'):route('portal.principal')));
$nav=[['Beranda',$portalHome,'home'],['Jadwal','#schedule','calendar'],['Akademik','#academic','chart'],['Info','#announcements','bell']];
@endphp
<div class="pointer-events-none fixed inset-x-0 top-0 h-80 bg-gradient-to-br from-emerald-950 via-emerald-800 to-cyan-700"></div>
<div class="relative mx-auto flex min-h-screen max-w-[1600px]">
    <aside class="sticky top-0 hidden h-screen w-72 shrink-0 p-5 lg:block"><div class="flex h-full flex-col rounded-[2rem] border border-white/10 bg-slate-950/90 p-5 text-slate-300 shadow-2xl backdrop-blur-xl"><a href="{{ $portalHome }}" class="flex items-center gap-3 text-white"><img src="/icons/smart-school.svg" class="size-12 rounded-2xl" alt="Smart School"><span class="font-black">Smart School<small class="block font-medium text-slate-400">{{ $portalTitle ?? 'Portal Digital' }}</small></span></a><nav class="mt-10 space-y-2">@foreach($nav as [$label,$href,$icon])<a href="{{ $href }}" class="group flex items-center gap-3 rounded-2xl px-4 py-3 font-semibold transition hover:bg-white/10 hover:text-white"><span class="grid size-9 place-items-center rounded-xl bg-white/5 text-lg">@if($icon==='home')⌂@elseif($icon==='calendar')▦@elseif($icon==='chart')◫@else◉@endif</span>{{ $label }}</a>@endforeach</nav><div class="mt-auto space-y-3"><button x-show="installable" x-cloak @click="installApp" class="flex w-full items-center justify-center gap-2 rounded-2xl bg-emerald-400 px-4 py-3 font-bold text-emerald-950">↓ Instal aplikasi</button><a href="{{ route('profile.edit') }}" class="flex items-center gap-3 rounded-2xl bg-white/5 p-3"><span class="grid size-10 place-items-center rounded-xl bg-emerald-400 font-black text-emerald-950">{{ str(auth()->user()->name)->substr(0,1)->upper() }}</span><span class="min-w-0"><b class="block truncate text-sm text-white">{{ auth()->user()->name }}</b><small class="text-slate-400">Kelola profil</small></span></a><form method="POST" action="{{ route('logout') }}">@csrf<button class="w-full rounded-xl border border-white/10 px-4 py-2 text-sm">Keluar</button></form></div></div></aside>
    <div class="min-w-0 flex-1 pb-28 lg:pb-8"><header class="sticky top-0 z-30 border-b border-white/10 bg-emerald-950/75 px-4 py-3 text-white backdrop-blur-xl sm:px-7 lg:top-4 lg:mx-7 lg:mt-4 lg:rounded-2xl lg:border"><div class="flex items-center justify-between"><a href="{{ $portalHome }}" class="flex items-center gap-3 lg:hidden"><img src="/icons/smart-school.svg" class="size-10 rounded-xl" alt=""><b>Smart School</b></a><div class="hidden lg:block"><p class="text-xs font-semibold uppercase tracking-[.2em] text-emerald-300">{{ $portalTitle ?? 'Portal Digital' }}</p><h1 class="font-bold">{{ $portalSubtitle ?? 'Satu ruang untuk aktivitas sekolah' }}</h1></div><div class="flex items-center gap-2"><span class="hidden rounded-full px-3 py-1 text-xs sm:inline-flex" :class="online?'bg-emerald-400/15 text-emerald-200':'bg-amber-400/20 text-amber-200'"><span x-text="online?'● Online':'● Offline'"></span></span><button x-show="installable" x-cloak @click="installApp" class="rounded-xl bg-white px-3 py-2 text-xs font-bold text-emerald-900 sm:px-4">Instal</button><a href="{{ route('profile.edit') }}" class="grid size-10 place-items-center rounded-xl bg-white/10 font-black">{{ str(auth()->user()->name)->substr(0,1)->upper() }}</a></div></div></header>
        <main class="px-4 py-6 sm:px-7 lg:py-8">@if(session('success'))<div class="mb-5 rounded-2xl border border-emerald-200 bg-emerald-50 p-4 text-sm font-semibold text-emerald-800">{{ session('success') }}</div>@endif @yield('content')</main>
    </div>
</div>
<nav class="fixed inset-x-3 bottom-3 z-40 grid grid-cols-4 rounded-[1.4rem] border border-white/50 bg-slate-950/95 p-2 text-white shadow-2xl backdrop-blur-xl lg:hidden" style="padding-bottom:max(.5rem,env(safe-area-inset-bottom))">@foreach($nav as [$label,$href,$icon])<a href="{{ $href }}" class="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-semibold transition active:scale-95 active:bg-white/10"><span class="text-xl leading-none">@if($icon==='home')⌂@elseif($icon==='calendar')▦@elseif($icon==='chart')◫@else◉@endif</span>{{ $label }}</a>@endforeach</nav>
</body></html>
