<!doctype html>
<html lang="id" class="scroll-smooth">
<head>
    <meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ $title ?? ($school?->name ?? config('app.name')) }}</title><meta name="description" content="{{ $description ?? $school?->short_description }}"><link rel="canonical" href="{{ $canonical ?? url()->current() }}">
    <meta property="og:title" content="{{ $title ?? ($school?->name ?? config('app.name')) }}"><meta property="og:description" content="{{ $description ?? $school?->short_description }}"><meta property="og:type" content="{{ $ogType ?? 'website' }}"><meta property="og:url" content="{{ $canonical ?? url()->current() }}">@isset($ogImage)<meta property="og:image" content="{{ $ogImage }}">@endisset
    <meta name="theme-color" content="#052e2b"><meta name="mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-capable" content="yes"><meta name="apple-mobile-web-app-status-bar-style" content="black-translucent"><link rel="manifest" href="/manifest.webmanifest"><link rel="icon" href="/icons/smart-school.svg" type="image/svg+xml"><link rel="apple-touch-icon" href="/icons/smart-school.svg">
    <script type="application/ld+json">{!! json_encode(['@context'=>'https://schema.org','@type'=>'School','name'=>$school?->name,'url'=>route('home'),'email'=>$school?->email,'telephone'=>$school?->phone,'address'=>['@type'=>'PostalAddress','streetAddress'=>$school?->address,'addressLocality'=>$school?->city,'addressRegion'=>$school?->province]], JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE) !!}</script>
    @vite(['resources/css/app.css','resources/js/app.js'])
</head>
<body class="bg-[#f4f7f6] pb-20 text-slate-900 antialiased lg:pb-0" x-data="pwaShell">
<header x-data="{open:false}" @keydown.escape.window="open=false" class="fixed inset-x-0 top-0 z-50 border-b border-white/10 bg-emerald-950/85 text-white shadow-lg shadow-emerald-950/10 backdrop-blur-xl">
    <div class="mx-auto flex h-16 max-w-7xl items-center justify-between px-4 sm:h-20 sm:px-6 lg:px-8"><a href="{{ route('home') }}" class="flex min-w-0 items-center gap-3"><img src="/icons/smart-school.svg" class="size-10 shrink-0 rounded-xl shadow-lg sm:size-11 sm:rounded-2xl" alt="Smart School"><span class="min-w-0 font-black leading-tight"><span class="block truncate text-sm sm:text-base">{{ $school?->name ?? 'Smart School' }}</span><small class="block truncate text-[10px] font-semibold text-emerald-200 sm:text-xs">School Information System</small></span></a>
        <nav class="hidden items-center gap-1 text-sm font-semibold lg:flex">@foreach($menus ?? [] as $menu)<a class="rounded-xl px-4 py-2.5 transition hover:bg-white/10 hover:text-amber-300" href="{{ $menu->url }}">{{ $menu->label }}</a>@endforeach<button x-show="installable" x-cloak @click="installApp" class="ml-2 rounded-xl border border-white/20 px-4 py-2.5">Instal</button><a href="{{ route('login') }}" class="ml-2 rounded-full bg-white px-5 py-2.5 font-bold text-emerald-950 shadow-lg">Portal Sekolah</a></nav>
        <div class="flex items-center gap-2 lg:hidden"><button x-show="installable" x-cloak @click="installApp" class="rounded-xl bg-white/10 px-3 py-2 text-xs font-bold">Instal</button><button @click="open=!open" class="grid size-10 place-items-center rounded-xl border border-white/15 bg-white/5 text-xl" aria-label="Buka navigasi" :aria-expanded="open"><span x-show="!open">☰</span><span x-show="open" x-cloak>×</span></button></div></div>
    <div x-show="open" x-cloak x-transition.opacity class="fixed inset-0 top-16 bg-slate-950/50 backdrop-blur-sm sm:top-20 lg:hidden" @click="open=false"></div>
    <nav x-show="open" x-cloak x-transition:enter="transition duration-200" x-transition:enter-start="-translate-y-3 opacity-0" x-transition:enter-end="translate-y-0 opacity-100" class="absolute inset-x-3 top-[4.5rem] max-h-[70vh] overflow-y-auto rounded-3xl border border-white/10 bg-slate-950 p-3 shadow-2xl sm:top-[5.5rem] lg:hidden">@foreach($menus ?? [] as $menu)<a @click="open=false" class="flex items-center justify-between rounded-2xl px-4 py-3.5 font-semibold hover:bg-white/10" href="{{ $menu->url }}"><span>{{ $menu->label }}</span><span class="text-slate-500">→</span></a>@endforeach<div class="mt-2 grid grid-cols-2 gap-2"><a class="rounded-2xl bg-amber-400 px-4 py-3 text-center font-bold text-emerald-950" href="{{ route('login') }}">Portal</a><button x-show="installable" @click="installApp" class="rounded-2xl bg-white/10 px-4 py-3 font-bold">Instal App</button></div></nav>
</header>
<main>{{ $slot ?? '' }}@yield('content')</main>
<footer id="kontak" class="relative overflow-hidden bg-slate-950 px-5 pb-20 pt-16 text-slate-300 lg:pb-14"><div class="absolute -right-32 -top-32 size-80 rounded-full bg-emerald-500/10 blur-3xl"></div><div class="relative mx-auto grid max-w-7xl gap-10 md:grid-cols-3"><div class="md:col-span-2"><div class="flex items-center gap-3"><img src="/icons/smart-school.svg" class="size-12 rounded-2xl" alt=""><div><div class="text-xl font-black text-white">{{ $school?->name }}</div><p class="text-xs text-emerald-300">Tumbuh · Berdaya · Menginspirasi</p></div></div><p class="mt-5 max-w-xl text-sm leading-7 text-slate-400">{{ $school?->short_description }}</p></div><div><p class="text-xs font-bold uppercase tracking-widest text-emerald-300">Hubungi kami</p><p class="mt-4 text-sm leading-7">{{ $school?->address }}, {{ $school?->city }}<br>{{ $school?->email }}<br>{{ $school?->phone }}</p></div></div><div class="relative mx-auto mt-10 flex max-w-7xl flex-wrap items-center justify-between gap-3 border-t border-white/10 pt-6 text-xs text-slate-500"><span>© {{ date('Y') }} {{ $school?->name }}</span><span x-text="online?'● Terhubung':'● Mode offline'" :class="online?'text-emerald-400':'text-amber-400'"></span></div></footer>
<nav aria-label="Navigasi utama mobile" class="fixed inset-x-3 bottom-3 z-50 grid grid-cols-5 rounded-[1.4rem] border border-white/10 bg-slate-950/95 p-2 text-white shadow-2xl backdrop-blur-xl lg:hidden" style="padding-bottom:max(.5rem,env(safe-area-inset-bottom))"><a href="{{ route('home') }}" class="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-semibold active:scale-95 active:bg-white/10"><span class="text-xl">⌂</span>Beranda</a><a href="{{ route('news.index') }}" class="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-semibold active:scale-95 active:bg-white/10"><span class="text-xl">▤</span>Berita</a><a href="{{ route('content.index','agenda') }}" class="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-semibold active:scale-95 active:bg-white/10"><span class="text-xl">▦</span>Agenda</a><a href="#kontak" class="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl text-[10px] font-semibold active:scale-95 active:bg-white/10"><span class="text-xl">◉</span>Kontak</a><a href="{{ route('login') }}" class="flex min-h-14 flex-col items-center justify-center gap-1 rounded-xl bg-emerald-500 text-[10px] font-black text-emerald-950 active:scale-95"><span class="text-xl">→</span>Portal</a></nav>
</body></html>
