@extends('layouts.admin', ['title'=>'Profil Sekolah', 'heading'=>'Profil Sekolah'])
@section('content')
<form method="POST" action="{{ route('admin.school-profile.update') }}" enctype="multipart/form-data" class="space-y-6">@csrf @method('PUT')
<section class="rounded-2xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Identitas utama</h2><p class="mt-1 text-sm text-slate-500">Informasi ini menjadi sumber tunggal untuk website dan dokumen sekolah.</p><div class="mt-6 grid gap-5 md:grid-cols-2">
@foreach([['name','Nama Sekolah','text'],['npsn','NPSN','text'],['nss','NSS','text'],['level','Jenjang','text'],['accreditation','Akreditasi','text'],['founded_year','Tahun Berdiri','number'],['email','Email','email'],['website','Website','url'],['phone','Telepon','text'],['whatsapp','WhatsApp','text']] as [$name,$label,$type])<label class="text-sm font-semibold">{{ $label }}<input name="{{ $name }}" type="{{ $type }}" value="{{ old($name,$school->$name) }}" class="mt-2 w-full rounded-xl border-slate-200 focus:border-emerald-500 focus:ring-emerald-500">@error($name)<span class="mt-1 block text-xs text-red-600">{{ $message }}</span>@enderror</label>@endforeach
<label class="text-sm font-semibold">Status<select name="status" class="mt-2 w-full rounded-xl border-slate-200">@foreach(['Negeri','Swasta'] as $status)<option @selected(old('status',$school->status)===$status)>{{ $status }}</option>@endforeach</select></label><label class="text-sm font-semibold">Tagline<input name="tagline" value="{{ old('tagline',$school->tagline) }}" class="mt-2 w-full rounded-xl border-slate-200"></label></div></section>
<section class="rounded-2xl bg-white p-6 shadow-sm"><h2 class="text-lg font-bold">Alamat & publikasi</h2><div class="mt-6 grid gap-5 md:grid-cols-2"><label class="text-sm font-semibold md:col-span-2">Deskripsi singkat<textarea name="short_description" rows="3" class="mt-2 w-full rounded-xl border-slate-200">{{ old('short_description',$school->short_description) }}</textarea></label><label class="text-sm font-semibold md:col-span-2">Alamat<textarea name="address" rows="2" class="mt-2 w-full rounded-xl border-slate-200">{{ old('address',$school->address) }}</textarea></label>@foreach(['village'=>'Desa/Kelurahan','district'=>'Kecamatan','city'=>'Kabupaten/Kota','province'=>'Provinsi','postal_code'=>'Kode Pos','latitude'=>'Latitude','longitude'=>'Longitude'] as $name=>$label)<label class="text-sm font-semibold">{{ $label }}<input name="{{ $name }}" value="{{ old($name,$school->$name) }}" class="mt-2 w-full rounded-xl border-slate-200"></label>@endforeach<label class="text-sm font-semibold">Logo<input name="logo" type="file" accept="image/png,image/jpeg,image/webp" class="mt-2 block w-full text-sm"></label><label class="text-sm font-semibold">Favicon<input name="favicon" type="file" accept="image/png,image/x-icon" class="mt-2 block w-full text-sm"></label></div></section>
<div class="sticky bottom-4 flex justify-end"><button class="rounded-full bg-emerald-700 px-7 py-3 font-bold text-white shadow-xl hover:bg-emerald-800">Simpan perubahan</button></div></form>
@endsection
